/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/geocode": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Geocode
     * @description Resolve a family-entered address, behind a per-IP budget.
     *
     *     The address is never stored; only the coordinates travel back. Nominatim's
     *     1 req/s policy is enforced inside geo.py for the whole process, so the
     *     limit here exists to stop one caller from consuming that shared budget.
     */
    post: operations["geocode_geocode_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Meta
     * @description Everything the frontend would otherwise hard-code.
     */
    get: operations["get_meta_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Programs
     * @description Programs in mapping order (region, rbd, program code), filtered and paged.
     *
     *     Filter semantics are ``data_loading.program_matches_filters``, so the API
     *     and the web filter panel can never drift apart.
     */
    get: operations["get_programs_programs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/programs/{program_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Program */
    get: operations["get_program_programs__program_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/recommend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Recommend
     * @description Suggest acceptable programs to append.
     *
     *     The current unmatched risk is recomputed server-side from the submitted
     *     list; a client-supplied risk would let the frontend steer the ranking.
     */
    post: operations["recommend_recommend_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/regions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Regions
     * @description Superseded by /meta.regions; kept for compatibility.
     */
    get: operations["get_regions_regions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/simulate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Simulate */
    post: operations["simulate_simulate_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** EquivalenceSensitivity */
    EquivalenceSensitivity: {
      /** Distinct Outcome Count */
      distinct_outcome_count: number;
      /** Outcome Stable */
      outcome_stable: boolean;
      /** Predicted Chance Max */
      predicted_chance_max: number | null;
      /** Predicted Chance Min */
      predicted_chance_min: number | null;
      /** Total Orders */
      total_orders: number;
      /** Variants */
      variants: components["schemas"]["SimulationVariant"][];
      /** Verdict */
      verdict: string;
    };
    /** EstimatedOutcome */
    EstimatedOutcome: {
      /** Label */
      label: string;
      /** Probability */
      probability: number;
      /** Program Id */
      program_id: string | null;
    };
    /** FilterOptions */
    FilterOptions: {
      /** Enrollment Fee */
      enrollment_fee: string[];
      /** Genders */
      genders: string[];
      /** Monthly Fee */
      monthly_fee: string[];
      /** Pace */
      pace: string[];
      /** Pie */
      pie: string[];
      /** Religious Orientation */
      religious_orientation: string[];
      /** Rurality */
      rurality: string[];
      /** School Days */
      school_days: string[];
      /** Specialty Sectors */
      specialty_sectors: string[];
      /** Tracks */
      tracks: string[];
    };
    /** GeocodeRequest */
    GeocodeRequest: {
      /** Address */
      address: string;
    };
    /** GeocodeResponse */
    GeocodeResponse: {
      /** Address */
      address: string;
      /** Display Name */
      display_name: string | null;
      /** Error Key */
      error_key: string | null;
      /** Lat */
      lat: number | null;
      /** Lon */
      lon: number | null;
      /** Message */
      message: string;
      /** Ok */
      ok: boolean;
      /** Params */
      params: {
        [key: string]: unknown;
      };
      /** Precision */
      precision: string | null;
      /** Warning Key */
      warning_key: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HomeLocation */
    HomeLocation: {
      /** Lat */
      lat: number;
      /** Lon */
      lon: number;
      /**
       * Precision
       * @default approximate
       */
      precision: string;
    };
    /** MetaResponse */
    MetaResponse: {
      /** Api Version */
      api_version: string;
      /** Data Fingerprint */
      data_fingerprint: string;
      /** Equiv Probability Change Warning Threshold */
      equiv_probability_change_warning_threshold: number;
      filter_options: components["schemas"]["FilterOptions"];
      /** Hard Unmatched Threshold */
      hard_unmatched_threshold: number;
      /** Max Exact Equiv Permutations */
      max_exact_equiv_permutations: number;
      /** Max Wishes */
      max_wishes: number;
      /** Recommendation Max Home Distance Km */
      recommendation_max_home_distance_km: number;
      /** Regions */
      regions: string[];
      /** Soft Unmatched Threshold */
      soft_unmatched_threshold: number;
    };
    /** ProgramListResponse */
    ProgramListResponse: {
      /** Items */
      items: components["schemas"]["ProgramSummary"][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total Matched */
      total_matched: number;
      /** Truncated */
      truncated: boolean;
    };
    /** ProgramSummary */
    ProgramSummary: {
      /** Calibration Imputed */
      calibration_imputed: boolean;
      /** Capacity */
      capacity: number;
      /** Program Display Name */
      program_display_name: string;
      /** Program Enrollment Fee */
      program_enrollment_fee: string;
      /** Program Gender */
      program_gender: string;
      /** Program Id */
      program_id: string;
      /** Program Label */
      program_label: string;
      /** Program Monthly Fee */
      program_monthly_fee: string;
      /** Program Pace */
      program_pace: string;
      /** Program Pie */
      program_pie: string;
      /** Program Religious Orientation */
      program_religious_orientation: string;
      /** Program Rurality */
      program_rurality: string;
      /** Program School Day */
      program_school_day: string;
      /** Program Specialty Sector */
      program_specialty_sector: string;
      /** Program Track */
      program_track: string;
      /** Region */
      region: string;
      /** School Commune */
      school_commune: string;
      /** School Name */
      school_name: string;
      /** True Applicants Last Year */
      true_applicants_last_year: number;
    };
    /** RecommendationDiagnostics */
    RecommendationDiagnostics: {
      /** Failed Candidate Examples */
      failed_candidate_examples: string[][];
      /** Failed Candidates */
      failed_candidates: number;
    };
    /**
     * RecommendationFilters
     * @description The step-2 sidebar filters, reused on step 4 to restrict the candidate
     *     pool. Same names and semantics as the ``GET /programs`` query parameters.
     */
    RecommendationFilters: {
      /** Enrollment Fee */
      enrollment_fee?: string[] | null;
      /** Gender */
      gender?: string[] | null;
      /** Monthly Fee */
      monthly_fee?: string[] | null;
      /** Pace */
      pace?: string[] | null;
      /** Pie */
      pie?: string[] | null;
      /** Region */
      region?: string | null;
      /** Religious Orientation */
      religious_orientation?: string[] | null;
      /** Rurality */
      rurality?: string[] | null;
      /** School Day */
      school_day?: string[] | null;
      /** Specialty Sector */
      specialty_sector?: string[] | null;
      /** Track */
      track?: string[] | null;
    };
    /** RecommendationItem */
    RecommendationItem: {
      /** Applicants Per Seat */
      applicants_per_seat: number | null;
      /** Capacity */
      capacity: number | null;
      /** Chance If Considered */
      chance_if_considered: number;
      /** Distance Km */
      distance_km: number | null;
      /** Estimated Mtb Rank */
      estimated_mtb_rank: number | null;
      /** Final Chance If Appended */
      final_chance_if_appended: number | null;
      /** Program Display Name */
      program_display_name: string;
      /** Program Id */
      program_id: string | null;
      /** Program Label */
      program_label: string;
      /** Projected Unmatched Risk */
      projected_unmatched_risk: number | null;
      /** Region */
      region: string;
      /** Risk Level */
      risk_level: string;
      /** School Commune */
      school_commune: string;
      /** School Name */
      school_name: string;
      /** Score */
      score: number;
    };
    /** RecommendationRequest */
    RecommendationRequest: {
      filters?: components["schemas"]["RecommendationFilters"] | null;
      home?: components["schemas"]["HomeLocation"] | null;
      /**
       * Max Recommendations
       * @default 5
       */
      max_recommendations: number;
      /**
       * Student Id
       * @description Student RUN/IPE, e.g. 12.345.678-9
       */
      student_id: string;
      /** Wishes */
      wishes: components["schemas"]["WishItem"][];
    };
    /** RecommendationResponse */
    RecommendationResponse: {
      /** Appended Wish Rank */
      appended_wish_rank: number;
      /** Current Unmatched Risk */
      current_unmatched_risk: number;
      diagnostics: components["schemas"]["RecommendationDiagnostics"];
      /** Distance Reference */
      distance_reference: string;
      /** Hard Distance Filter Applied */
      hard_distance_filter_applied: boolean;
      /** Items */
      items: components["schemas"]["RecommendationItem"][];
      /** Limited By Filters */
      limited_by_filters: boolean;
      /** Similarity Fallback Mode */
      similarity_fallback_mode: boolean;
    };
    /** SimulationRequest */
    SimulationRequest: {
      /**
       * Student Id
       * @description Student RUN/IPE, e.g. 12.345.678-9
       */
      student_id: string;
      /** Wishes */
      wishes: components["schemas"]["WishItem"][];
    };
    /** SimulationResponse */
    SimulationResponse: {
      /** At Risk */
      at_risk: boolean;
      /** Attention Level */
      attention_level: string;
      equivalence_sensitivity?:
        components["schemas"]["EquivalenceSensitivity"] | null;
      /** Outcomes */
      outcomes: components["schemas"]["EstimatedOutcome"][];
      /** Predicted Outcome */
      predicted_outcome: string;
      /** Predicted Outcome Program Id */
      predicted_outcome_program_id: string | null;
      thresholds: components["schemas"]["Thresholds"];
      /** Unmatched Risk */
      unmatched_risk: number;
      /** Wishes */
      wishes: components["schemas"]["WishResult"][];
    };
    /** SimulationVariant */
    SimulationVariant: {
      /** At Risk */
      at_risk: boolean;
      /** Order Index */
      order_index: number;
      /** Predicted Outcome */
      predicted_outcome: string;
      /** Predicted Outcome Final Chance */
      predicted_outcome_final_chance: number | null;
      /** Predicted Outcome Program Id */
      predicted_outcome_program_id: string | null;
      /** Program Order */
      program_order: string[];
      /** Tied Order */
      tied_order: string[][];
      /** Unmatched Risk */
      unmatched_risk: number;
    };
    /** Thresholds */
    Thresholds: {
      /** Hard */
      hard: number;
      /** Soft */
      soft: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** WishItem */
    WishItem: {
      /**
       * Equivalence Group
       * @description Wishes sharing the same group are treated as tied; lower numbers are preferred over higher ones. Omit for strict ranking, where each wish defaults to its own group equal to its position in the list.
       */
      equivalence_group?: number | null;
      /**
       * Priority Already Registered
       * @default false
       */
      priority_already_registered: boolean;
      /**
       * Priority Ex Student
       * @default false
       */
      priority_ex_student: boolean;
      /**
       * Priority Parent Civil Servant
       * @default false
       */
      priority_parent_civil_servant: boolean;
      /**
       * Priority Sibling
       * @default false
       */
      priority_sibling: boolean;
      /**
       * Priority Student
       * @default false
       */
      priority_student: boolean;
      /** Program Id */
      program_id: string;
    };
    /** WishResult */
    WishResult: {
      /** Availability Probability */
      availability_probability: number;
      /** Calibration Imputed */
      calibration_imputed: boolean;
      /** Capacity */
      capacity: number;
      /** Choice Assignment Probability */
      choice_assignment_probability: number;
      /** Cumulative Unavailable Before Choice */
      cumulative_unavailable_before_choice: number;
      /** Lottery Number */
      lottery_number: number;
      /** Lottery Population Used */
      lottery_population_used: number;
      /** Priority Tier */
      priority_tier: string;
      /** Program Id */
      program_id: string;
      /** Program Label */
      program_label: string;
      /** True Applicants Last Year */
      true_applicants_last_year: number;
      /** Wish Rank */
      wish_rank: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  geocode_geocode_post: {
    parameters: {
      query?: {
        /** @description Language for `message` fields: es (default) or en. */
        lang?: string | null;
      };
      header?: {
        "Accept-Language"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeocodeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GeocodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_meta_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MetaResponse"];
        };
      };
    };
  };
  get_programs_programs_get: {
    parameters: {
      query?: {
        /** @description Exact region name, as returned by /regions */
        region?: string | null;
        /** @description Free-text search over school name, commune, and program name */
        q?: string | null;
        limit?: number;
        offset?: number;
        track?: string[] | null;
        specialty_sector?: string[] | null;
        gender?: string[] | null;
        school_day?: string[] | null;
        rurality?: string[] | null;
        pie?: string[] | null;
        pace?: string[] | null;
        enrollment_fee?: string[] | null;
        monthly_fee?: string[] | null;
        religious_orientation?: string[] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_program_programs__program_id__get: {
    parameters: {
      query?: {
        /** @description Language for `message` fields: es (default) or en. */
        lang?: string | null;
      };
      header?: {
        "Accept-Language"?: string | null;
      };
      path: {
        program_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProgramSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  recommend_recommend_post: {
    parameters: {
      query?: {
        /** @description Language for `message` fields: es (default) or en. */
        lang?: string | null;
      };
      header?: {
        "Accept-Language"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecommendationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RecommendationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_regions_regions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  simulate_simulate_post: {
    parameters: {
      query?: {
        /** @description Language for `message` fields: es (default) or en. */
        lang?: string | null;
      };
      header?: {
        "Accept-Language"?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SimulationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SimulationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
